data_dir = "data"
demographics_file = "demographics.csv"
primary_id_column = "ursi"
session_column = "session_num"
composite_id_column = "customID"
default_age_min = 6
default_age_max = 95
max_display_rows = 50
default_sex_selection = [ "Female", "Male",]

[sex_mapping]
Female = 1.0
Male = 2.0
Other = 3.0
Unspecified = 0.0
